const { nextui } = require("@nextui-org/react");
/** @type {import('tailwindcss').Config} */

module.exports = {
  // important: true,
  content: [
    "./our_pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      animation: {
        "up-down": "upDown 2s ease-in-out infinite",
        "float-bob": "floatBob 2s linear infinite",
      },
      keyframes: {
        upDown: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        floatBob: {
          "0%, 100%": { transform: "translateY(-30px)" },
          "50%": { transform: "translateY(-15px)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        primary: "#FFD000",
        secondary: "#3F3F3E",
        accent: "#E4E5E6",
        neutral: "#315d89",
        dark: "#3F3F3E",
        medium: "E4E5E6",
        p: "#F2F2F2",
        "p-dark": "#030303",
        e1: "#F7F7F7",
        "e1-dark": "#111111",
        e2: "#EBEBEB",
        "e2-dark": "#242424",
        tm: "#111111",
        "tm-dark": "#F9F9F9",
        ts: "#666666",
        "ts-dark": "#A6A6A6",
        tl: "#CCCCCC",
        "tl-dark": "#333333",
        g: "#0F9D58",
        "g-dark": "#10A85E",
        gb: "rgba(15, 157, 88, 0.1)",
        "gb-dark": "rgba(16, 168, 94, 0.14)",
        r: "#C81313",
        "r-dark": "#E01515",
        rb: "rgba(200, 19, 19, 0.1)",
        "rb-dark": "rgba(224, 21, 21, 0.14)",
        b: "#1151B1",
        "b-dark": "#1259C4",
        bb: "rgba(17, 81, 177, 0.1)",
        "bb-dark": "rgba(18, 89, 196, 0.14)",
        pc: "#CBA700",
        "pc-dark": "#FED100",
        nw: "#F9F9F9",
        "nw-dark": "#F9F9F9",
        nb: "#111111",
        "nb-dark": "#111111",
        cc: "#FCFCFC",
        "cc-dark": "#1A1A1A",
        pcp: "#FED100",
        "pcp-dark": "#FED100",
        pbg: "#F2F2F2",
        "pbg-dark": "#030303",
        wp: "#ffffff",
        "wp-dark": "#ffffff",
        bp: "#000000",
        "bp-dark": "#000000",
      },
      fontFamily: {
        montserrat: ["var(--font-montserrat)"],
        kufi: ["var(--font-kufi)"],
      },
      screens: {
        xs: { max: "639px" },
      },
    },
  },
  darkMode: "class",
  plugins: [nextui()],
};
