import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import localFont from "@next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = localFont({
  src: [
    {
      path: "../../public/fonts/Montserrat/Montserrat-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Montserrat/Montserrat-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/Montserrat/Montserrat-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/Montserrat/Montserrat-Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-montserrat",
});

// const kufi = localFont({
//   src: [
//     {
//       path: "../../public/fonts/Kufi/NotoKufiArabic-Regular.ttf",
//       weight: "400",
//     },
//     {
//       path: "../../public/fonts/Kufi/NotoKufiArabic-Medium.ttf",
//       weight: "500",
//     },
//     {
//       path: "../../public/fonts/Kufi/NotoKufiArabic-Bold.ttf",
//       weight: "700",
//     },
//     {
//       path: "../../public/fonts/Kufi/NotoKufiArabic-Black.ttf",
//       weight: "900",
//     },
//   ],
//   variable: "--font-kufi",
// });

export default async function layout({ children, params: { locale } }) {
  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";
  return (
    <html className={montserrat.variable} lang={locale} dir={direction}>
      <body>
        <NextUIProvider>
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
            <Footer />
          </NextIntlClientProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
