import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { NextIntlClientProvider, createTranslator } from "next-intl";
import { getMessages } from "next-intl/server";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import localFont from "@next/font/local";
import Cookies from "@/components/Cookies";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const montserrat = localFont({
  src: [
    {
      path: "../../public/fonts/Montserrat/Montserrat-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Montserrat/Montserrat-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/Montserrat/Montserrat-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/Montserrat/Montserrat-Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-montserrat",
});

export async function generateMetadata({ params: { locale } }) {
  const messages = (await import(`../../messages/${locale}.json`)).default;
  const t = createTranslator({ locale, messages });
  const url =
    locale != "en"
      ? `${process.env.NEXT_PUBLIC_BASE_URL}/${locale}`
      : `${process.env.NEXT_PUBLIC_BASE_URL}`;

  return {
    title: t("home.metaData.title"),
    description: t("home.metaData.description"),
    alternates: {
      canonical: url,
    },
  };
}

export default async function layout({ children, params: { locale } }) {
  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";
  return (
    <html className={montserrat.variable} lang={locale} dir={direction}>
      <body>
        <NextUIProvider>
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
            <Footer />
            <Cookies />
          </NextIntlClientProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
